language: elixir

elixir:
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"

otp_release:
  - 22.0
  - 23.3
  - 24.0

env:
  - WEBDRIVER=selenium

matrix:
  exclude:
    - elixir: "1.9"
      otp_release: 22.0
    - elixir: "1.10"
      otp_release: 22.0
    - elixir: "1.11"
      otp_release: 23.3
    - elixir: "1.12"
      otp_release: 23.3
    - elixir: "1.12"
      otp_release: 24.0

before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - bash $TRAVIS_BUILD_DIR/test/tools/start_webdriver.sh

script: mix test --exclude=issue_travis_${WEBDRIVER}
